from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Any

from config import BOT_NAME, STATS_FILE


logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
LOGGER = logging.getLogger(__name__)


def _wrap_section(section_name: str, body: str) -> str:
    return f"<!-- SECTION:{section_name} -->\n{body}\n<!-- END:{section_name} -->"


def build_header_section() -> str:
    body = (
        "# 🧬 AI Idea Resurrection Lab\n\n"
        "> Abandoned GitHub issues, brought back to life by AI.\n"
        "> Every day: one forgotten idea gets a full technical analysis,\n"
        "> working proof-of-concept code, and an impact score.\n\n"
        "![updates daily](https://img.shields.io/badge/updates-daily-brightgreen)\n"
        "![powered by GPT-4o](https://img.shields.io/badge/powered%20by-GPT--4o-blue)\n"
        "![license MIT](https://img.shields.io/badge/license-MIT-orange)"
    )
    return _wrap_section("header", body)


def build_stats_section(progress: dict[str, Any]) -> str:
    total_resurrections = int(progress.get("total_resurrections", 0))
    total_repos_covered = int(progress.get("total_repos_covered", 0))
    average_impact_score = float(progress.get("average_impact_score", 0.0))
    average_effort_hours = float(progress.get("average_effort_hours", 0.0))
    subscriber_count = int(progress.get("subscriber_count", 0))
    last_updated = str(progress.get("last_updated", ""))

    body = (
        "## 📊 Live Stats\n\n"
        "| Metric | Value |\n"
        "|--------|-------|\n"
        f"| 🧬 Total Resurrections | {total_resurrections} |\n"
        f"| 🗂️ Repos Covered | {total_repos_covered} |\n"
        f"| 💥 Avg Impact Score | {average_impact_score}/10 |\n"
        f"| ⏱️ Avg Effort | ~{average_effort_hours}h |\n"
        f"| 📬 Subscribers | {subscriber_count} |\n"
        f"| 🕐 Last Updated | {last_updated} |"
    )
    return _wrap_section("stats", body)


def build_hall_of_fame_section(progress: dict[str, Any]) -> str:
    hall = progress.get("hall_of_fame", [])
    lines: list[str] = ["## 🏆 Hall of Fame", ""]
    if not isinstance(hall, list) or not hall:
        lines.append("> *No resurrections yet. Check back tomorrow.*")
        return _wrap_section("hall-of-fame", "\n".join(lines))

    for rank, entry in enumerate(hall[:3], start=1):
        if not isinstance(entry, dict):
            continue
        title = str(entry.get("title", "Untitled"))
        repo = str(entry.get("repo", ""))
        impact_score = int(entry.get("impact_score", 0))
        one_line_why = str(entry.get("one_line_why", ""))
        original_url = str(entry.get("original_url", ""))

        lines.extend(
            [
                f"### {rank}. {title}",
                f"**Repo:** {repo} | **Impact:** {impact_score}/10",
                f"> {one_line_why}",
                f"[View Original Issue]({original_url})",
                "",
            ]
        )

    return _wrap_section("hall-of-fame", "\n".join(lines).strip())


def build_last_section(progress: dict[str, Any]) -> str:
    last = progress.get("last_resurrection")
    lines: list[str] = ["## 🔬 Latest Resurrection", ""]

    if isinstance(last, dict):
        title = str(last.get("title", "Untitled"))
        original_url = str(last.get("original_url", ""))
        repo = str(last.get("repo", ""))
        impact_score = int(last.get("impact_score", 0))
        date = str(last.get("date", ""))
        one_line_why = str(last.get("one_line_why", ""))
        lines.extend(
            [
                f"**[{title}]({original_url})**",
                f"📦 `{repo}` · 💥 Impact: `{impact_score}/10` · 🗓️ `{date}`",
                f"> {one_line_why}",
            ]
        )
    else:
        lines.append("> *The first resurrection is coming soon.*")

    return _wrap_section("last", "\n".join(lines))


def build_subscribe_section() -> str:
    body = (
        "## 📬 Stay Ahead of the Curve\n\n"
        "> ** `https://mohaabdelkarim.gumroad.com/l/ai-tool-drop` ** —\n"
        "> The free weekly newsletter that cuts through the AI noise.\n"
        "> Every week: one fresh AI tool tested honestly, a real workflow\n"
        "> under 30 minutes, a straight verdict.\n"
        "> **Free. No paywalls. No affiliate links.**\n\n"
        "`https://mohaabdelkarim.gumroad.com/l/ai-tool-drop`"
    )
    return _wrap_section("subscribe", body)


def build_footer_section(progress: dict[str, Any]) -> str:
    last_updated = str(progress.get("last_updated", ""))
    body = f"---\n*Auto-generated by {BOT_NAME} · Last run: {last_updated}*"
    return _wrap_section("footer", body)


def replace_section(content: str, section_name: str, new_section: str) -> str:
    start_marker = f"<!-- SECTION:{section_name} -->"
    end_marker = f"<!-- END:{section_name} -->"
    start = content.find(start_marker)
    end = content.find(end_marker)

    if start != -1 and end != -1 and end >= start:
        end_inclusive = end + len(end_marker)
        before = content[:start].rstrip()
        after = content[end_inclusive:].lstrip()
        if before and after:
            return f"{before}\n\n{new_section}\n\n{after}"
        if before:
            return f"{before}\n\n{new_section}"
        if after:
            return f"{new_section}\n\n{after}"
        return new_section

    if content.strip():
        return f"{content.rstrip()}\n\n{new_section}"
    return new_section


def generate_readme(progress: dict[str, Any]) -> str:
    content = ""
    content = replace_section(content, "header", build_header_section())
    content = replace_section(content, "stats", build_stats_section(progress))
    content = replace_section(content, "hall-of-fame", build_hall_of_fame_section(progress))
    content = replace_section(content, "last", build_last_section(progress))
    content = replace_section(content, "subscribe", build_subscribe_section())
    content = replace_section(content, "footer", build_footer_section(progress))
    return content.rstrip() + "\n"


def update_readme() -> None:
    try:
        from scripts.stats import load_progress
    except ImportError:
        script_dir = Path(__file__).parent
        sys.path.insert(0, str(script_dir))
        from stats import load_progress

    progress = load_progress()
    readme_content = generate_readme(progress)

    repo_root = Path(STATS_FILE).parent.parent
    readme_path = repo_root / "README.md"
    readme_path.write_text(readme_content, encoding="utf-8")
    LOGGER.info("README.md updated successfully")
